### ISSUE TITLE
stand storage

### ISSUE THREAD

**Issue by oreodelph** [delphe/JoJoGame#15]
Create an NPC. On click, show catalog with 10 empty boxes.
If you have a stand you can click on an empty box to insert your stand and your stand will go away.
If a box is not empty (image of a stand), click on it to obtain the stand. If you already have one, it will swap it out.

**Comment by delphe** [comment]
Create an NPC. On click, show catalog with 10 empty boxes.
If you have a stand you can click on an empty box to insert your stand and your stand will go away.
If a box is not empty (image of a stand), click on it to obtain the stand. If you already have one, it will swap it out.
